basePath: /
definitions:
  github_com_SlayerSv_payments_internal_shared_errs.Response:
    properties:
      error:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_shared_models.DepositRequest:
    properties:
      amount:
        type: integer
    required:
    - amount
    type: object
  github_com_SlayerSv_payments_internal_shared_models.EmailDTO:
    properties:
      email:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_shared_models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_shared_models.LoginResponse:
    properties:
      token:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_shared_models.NewBalanceResponse:
    properties:
      new_balance:
        type: integer
    type: object
  github_com_SlayerSv_payments_internal_shared_models.TransactionDTO:
    properties:
      amount:
        type: integer
      completed_at:
        type: string
      donor_email:
        type: string
      donor_name:
        type: string
      donor_wallet_id:
        type: string
      id:
        type: string
      op_type:
        type: string
      receiver_email:
        type: string
      receiver_name:
        type: string
      receiver_wallet_id:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_shared_models.TransactionHistory:
    properties:
      transactions:
        items:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.TransactionDTO'
        type: array
    type: object
  github_com_SlayerSv_payments_internal_shared_models.TransferRequest:
    properties:
      amount:
        type: integer
      receiver_wallet_id:
        type: string
    required:
    - amount
    - receiver_wallet_id
    type: object
  github_com_SlayerSv_payments_internal_shared_models.UpdateUserRequest:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_shared_models.UserDTO:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_shared_models.WalletDTO:
    properties:
      balance:
        type: integer
      created_at:
        type: string
      id:
        type: string
      owner_id:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_shared_models.WalletID:
    properties:
      id:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_shared_models.WalletsDTO:
    properties:
      wallets:
        items:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.WalletDTO'
        type: array
    type: object
  github_com_SlayerSv_payments_internal_shared_models.WithdrawRequest:
    properties:
      amount:
        type: integer
    required:
    - amount
    type: object
host: localhost:8081
info:
  contact: {}
  description: API Server for Payments system
  termsOfService: http://swagger.io/terms/
  title: Payments API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and signs a JWT token
      parameters:
      - description: Login Credentials
        in: body
        name: email&password
        required: true
        schema:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      summary: User Login
      tags:
      - auth
  /me:
    get:
      consumes:
      - application/json
      description: Gets user`s wallet information (name, email).
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.UserDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Gets user's wallet information
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Updates user (name, password).
      parameters:
      - description: New name and/or password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.UserDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Updates user
      tags:
      - users
  /me/wallets:
    get:
      consumes:
      - application/json
      description: Gets all user`s wallets
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.WalletsDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Gets all user's wallets
      tags:
      - wallets
    post:
      consumes:
      - application/json
      description: Creates wallet
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.WalletID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Creates wallet
      tags:
      - wallets
  /me/wallets/{wallet_id}:
    delete:
      consumes:
      - application/json
      description: Deletes wallet
      parameters:
      - description: Wallet ID
        in: path
        name: wallet_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Deletes wallet
      tags:
      - wallets
    get:
      consumes:
      - application/json
      description: Gets user`s wallet information.
      parameters:
      - description: Wallet ID
        in: path
        name: wallet_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.WalletDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Gets user's wallet information
      tags:
      - wallets
  /me/wallets/{wallet_id}/deposit:
    post:
      consumes:
      - application/json
      description: Deposits funds to a specified wallet
      parameters:
      - description: wallet ID
        in: path
        name: wallet_id
        required: true
        type: string
      - description: Amount to deposit
        in: body
        name: amount
        required: true
        schema:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.DepositRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.NewBalanceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Deposits funds to a specified wallet
      tags:
      - transactions
  /me/wallets/{wallet_id}/transactions:
    get:
      consumes:
      - application/json
      description: Gets history of transactions of an wallet
      parameters:
      - description: wallet ID
        in: path
        name: wallet_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.TransactionHistory'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Gets history of transactions of an wallet
      tags:
      - transactions
  /me/wallets/{wallet_id}/transfer:
    post:
      consumes:
      - application/json
      description: Transfers funds to a specified wallet
      parameters:
      - description: wallet ID
        in: path
        name: wallet_id
        required: true
        type: string
      - description: Transfer details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.TransferRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.NewBalanceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Transfers funds to a specified wallet
      tags:
      - transactions
  /me/wallets/{wallet_id}/withdraw:
    post:
      consumes:
      - application/json
      description: Withdraws funds from a specified wallet
      parameters:
      - description: wallet ID
        in: path
        name: wallet_id
        required: true
        type: string
      - description: Amount to withdraw
        in: body
        name: amount
        required: true
        schema:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.WithdrawRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.NewBalanceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Withdraws funds from a specified wallet
      tags:
      - transactions
  /register:
    post:
      consumes:
      - application/json
      description: Creates a new user wallet and sends a one time password to the
        user's email
      parameters:
      - description: Email of the user
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.EmailDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      summary: Register User
      tags:
      - auth
  /restore:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email of a user
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_models.EmailDTO'
      responses:
        "204":
          description: No Content
      security:
      - BearerAuth: []
      summary: Creates a one-time password for a user with a certain email, saves
        it to a database and sends to the user
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
