basePath: /
definitions:
  github_com_SlayerSv_payments_internal_auth_models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_auth_models.LoginResponse:
    properties:
      token:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_auth_models.RegisterRequest:
    properties:
      email:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_auth_models.UpdateUserRequest:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_auth_models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_shared_errs.Response:
    properties:
      error:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_trans_models.DepositRequest:
    properties:
      account_type:
        type: string
      amount:
        type: integer
    required:
    - account_type
    - amount
    type: object
  github_com_SlayerSv_payments_internal_trans_models.NewBalanceResponse:
    properties:
      new_balance:
        type: integer
    type: object
  github_com_SlayerSv_payments_internal_trans_models.TransactionDTO:
    properties:
      amount:
        type: integer
      completed_at:
        type: string
      donor_account_id:
        type: string
      donor_account_type:
        type: string
      donor_email:
        type: string
      donor_name:
        type: string
      id:
        type: string
      op_type:
        type: string
      receiver_account_id:
        type: string
      receiver_account_type:
        type: string
      receiver_email:
        type: string
      receiver_name:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_trans_models.TransferRequest:
    properties:
      amount:
        type: integer
      donor_account_type:
        type: string
      receiver_account_id:
        type: string
      receiver_account_type:
        type: string
    required:
    - amount
    - donor_account_type
    - receiver_account_id
    - receiver_account_type
    type: object
  github_com_SlayerSv_payments_internal_trans_models.WithdrawRequest:
    properties:
      account_type:
        type: string
      amount:
        type: integer
    required:
    - account_type
    - amount
    type: object
  github_com_SlayerSv_payments_internal_wallet_models.AccountResponse:
    properties:
      balance:
        type: integer
      created_at:
        type: string
      id:
        type: string
      owner_id:
        type: string
    type: object
  github_com_SlayerSv_payments_internal_wallet_models.AccountsResponse:
    properties:
      accounts:
        items:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_wallet_models.AccountResponse'
        type: array
    type: object
  internal_gateway_api_http.AccountID:
    properties:
      id:
        type: string
    type: object
  internal_gateway_api_http.History:
    properties:
      transactions:
        items:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_trans_models.TransactionDTO'
        type: array
    type: object
  internal_gateway_api_http.OTPRequest:
    properties:
      email:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API Server for Payments system
  termsOfService: http://swagger.io/terms/
  title: Payments API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and signs a JWT token
      parameters:
      - description: Login Credentials
        in: body
        name: email&password
        required: true
        schema:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_auth_models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_auth_models.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      summary: User Login
      tags:
      - auth
  /me:
    get:
      consumes:
      - application/json
      description: Gets user`s account information (name, email).
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_auth_models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Gets user's account information
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Updates user (name, password).
      parameters:
      - description: New name and/or password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_auth_models.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_auth_models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Updates user
      tags:
      - users
  /me/accounts:
    get:
      consumes:
      - application/json
      description: Gets user`s all wallet/savings accounts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_wallet_models.AccountsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Gets user's all wallet/savings accounts
      tags:
      - accounts
    post:
      consumes:
      - application/json
      description: Creates wallet/savings account
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_gateway_api_http.AccountID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Creates wallet/savings account
      tags:
      - accounts
  /me/accounts/{account_id}:
    delete:
      consumes:
      - application/json
      description: Deletes wallet/savings account
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Deletes wallet/savings account
      tags:
      - accounts
    get:
      consumes:
      - application/json
      description: Gets user`s wallet/savings account information.
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_wallet_models.AccountResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Gets user's wallet/savings account information
      tags:
      - accounts
  /me/accounts/{account_id}/deposit:
    post:
      consumes:
      - application/json
      description: Deposits funds to a specified account
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: string
      - description: Amount to deposit
        in: body
        name: amount
        required: true
        schema:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_trans_models.DepositRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_trans_models.NewBalanceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Deposits funds to a specified account
      tags:
      - transactions
  /me/accounts/{account_id}/transactions:
    get:
      consumes:
      - application/json
      description: Gets history of transactions of an account
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_gateway_api_http.History'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Gets history of transactions of an account
      tags:
      - transactions
  /me/accounts/{account_id}/transfer:
    post:
      consumes:
      - application/json
      description: Transfers funds to a specified account
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: string
      - description: Transfer details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_trans_models.TransferRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_trans_models.NewBalanceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Transfers funds to a specified account
      tags:
      - transactions
  /me/accounts/{account_id}/withdraw:
    post:
      consumes:
      - application/json
      description: Withdraws funds from a specified account
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: string
      - description: Amount to withdraw
        in: body
        name: amount
        required: true
        schema:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_trans_models.WithdrawRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_trans_models.NewBalanceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      security:
      - BearerAuth: []
      summary: Withdraws funds from a specified account
      tags:
      - transactions
  /register:
    post:
      consumes:
      - application/json
      description: Creates a new user account and sends a one time password to the
        user's email
      parameters:
      - description: Email of the user
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/github_com_SlayerSv_payments_internal_auth_models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_SlayerSv_payments_internal_shared_errs.Response'
      summary: Register User
      tags:
      - auth
  /restore:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email of a user
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/internal_gateway_api_http.OTPRequest'
      responses:
        "204":
          description: No Content
      security:
      - BearerAuth: []
      summary: Creates a one-time password for a user with a certain email, saves
        it to a database and sends to the user
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
